language: node_js
node_js:
  # 10.13 includes npm@6 which has good "npm ci" command, and is LTS
  - 10.13

# stop building all branches and pull requests
# until they have been merged
# https://github.com/cypress-io/cypress-example-recipes/issues/260
branches:
  only:
  - master

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci

# common build steps for each recipe
defaults: &defaults
  script:
    - cd examples/$DIR
    - echo current dir $PWD || true
    - npm start -- --silent &
    - date -R # run starts timestamp
    # Travis CI has very unpredictable scheduling, breaking recording
    # due to long time gaps between the test jobs
    # https://github.com/cypress-io/cypress-example-recipes/issues/243
    # Disabling recording for now
    - npm run cypress:run
    - date -R # run finishes timestamp
    # kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

jobs:
  include:
    # define a separate script for each "examples/*" folder
    # this will run it in a separate job on TravisCI

    # skip Codepen demo because Codepen is 502
    # - stage: test
    #   env:
    #     - DIR=blogs__codepen-demo
    #   <<: *defaults
    - stage: test
      env:
        - DIR=blogs__direct-control-angular
      <<: *defaults
    - stage: test
      env:
        - DIR=blogs__e2e-api-testing
      <<: *defaults
    - stage: test
      env:
        - DIR=blogs__e2e-snapshots
      <<: *defaults
    - stage: test
      env:
        - DIR=blogs__testing-redux-store
      <<: *defaults
    - stage: test
      env:
        - DIR=blogs__vue-vuex-rest
      <<: *defaults
    - stage: test
      env:
        - DIR=extending-cypress__chai-assertions
      <<: *defaults
    - stage: test
      env:
        - DIR=file-upload-react
      <<: *defaults
    - stage: test
      env:
        - DIR=fundamentals__node-modules
      <<: *defaults
    - stage: test
      env:
        - DIR=logging-in__csrf-tokens
      <<: *defaults
    - stage: test
      env:
        - DIR=logging-in__html-web-forms
      <<: *defaults
    - stage: test
      env:
        - DIR=logging-in__single-sign-on
      <<: *defaults
    - stage: test
      env:
        - DIR=logging-in__xhr-web-forms
      <<: *defaults
    - stage: test
      env:
        - DIR=preprocessors__typescript-browserify
      <<: *defaults
    - stage: test
      env:
        - DIR=preprocessors__typescript-webpack
      <<: *defaults
    - stage: test
      env:
        - DIR=server-communication__bootstrapping-your-app
      <<: *defaults
    - stage: test
      env:
        - DIR=stubbing-spying__functions
      <<: *defaults
    - stage: test
      env:
        - DIR=stubbing-spying__window-fetch
      <<: *defaults
    - stage: test
      env:
        - DIR=testing-dom__drag-drop
      <<: *defaults
    - stage: test
      env:
        - DIR=testing-dom__form-interactions
      <<: *defaults
    - stage: test
      env:
        - DIR=testing-dom__hover-hidden-elements
      <<: *defaults
    - stage: test
      env:
        - DIR=testing-dom__tab-handling-links
      <<: *defaults
    - stage: test
      env:
        - DIR=unit-testing__application-code
      <<: *defaults
    - stage: test
      env:
        - DIR=unit-testing__react
      <<: *defaults
    - stage: test
      env:
        - DIR=server-communication__env-variables
      <<: *defaults

notifications:
  slack:
    secure: ne0CixoRITDhePGEGgxDYnwB7DxoMhuFO6NWJKqgzs6Cz/uwwWJ9DAVgjbbh6HWaWLhHaew0s4Bx3Ckyk2AfqzmrPhVJCWZsx7VihrniGZCn/sZk/VQ71O/XDXlEw2d7Gm65Uu9MtesB98sCQsbr69cAJzZWd4A/6R/7nWsLmzM7KG1ZnEHDhNFI5KY/dAA7ImZ7q9pc5Zw1JeAMW7X4nGpDRhXcxk2FxVNge5m4GOhlFfb/CPNwo/FC9MbE+GrfpyQNK5J0DRkdu7igs8dbTJFEEjGLCVbxLZD5X5GZwRJmN3G5Zt89bs/ZHwj4tBKWKZeSxEbrrOr/OilFF3N46QhJSTjF7DgG2BlITYi3ZgHSUC/OanfxjoGYMrd702Nq9Wod3ZbhiwTbAwBOkkfv9+g12fwTk+u5BgNhcweHbdP3Ju5dmD53Z7rY4kIP0XlhfvU5WvC6YuKzVxquZQFEAWYzkcBPiZh2UP9hxuBRdX5UcLoU2eBGAUa8LlPhMO15i5sXyfH1vjnKkzgf1n8I7RQcWvpTBnAZyLwjT4bnqwP7gBYt/heO+iSGVaIya3ShtocwBxv9l88Qe6ogsHAHLnjaK352hVc5+6s7WyECXQ2EZug8GXlahHkLn3dXEY+zVNclyG0rNSDMRDQO5LsrXVr7zjyxHHrEWWBvHfePfb0=
