# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node -e "console.log(process.platform)"
  - node -e "console.log(process.arch)"
  # print cached dependencies
  - echo '%AppData%\npm-cache'
  - echo '%USERPROFILE%\AppData\Local\Cypress\Cache'
  - ls '%AppData%\npm-cache' || true
  - ls '%USERPROFILE%\AppData\Local\Cypress\Cache' || true
  - npm ci
  # install global bin-up
  # to avoid problems with finding tool paths on Windows
  - npm i -g bin-up

cache:
  # cache NPM packages and Cypress binary
  # https://www.appveyor.com/docs/build-cache/
  # https://docs.npmjs.com/files/folders.html#cache
  # https://on.cypress.io/caching
  - '%AppData%\npm-cache'
  - '%USERPROFILE%\AppData\Local\Cypress\Cache'
  # Note: by default cache is only saved for successful builds
  # you can save cache from the failed builds
  # using APPVEYOR_SAVE_CACHE_ON_ERROR: true environment variable

test_script:
  - npm run test:ci:windows

# Don't actually build, we are only interested in tests
build: off
